### PR TITLE
Docker pr iteration 3

### PR DESCRIPTION
**Pull request by arranubels**
This supersedes #21.

This adds tests. Makes docker more powerful. Does everything #21 does. Incorporates some of the other PRs to make it into master. And contains no snakes oil!

### CODE REVIEW

**Comment by aaronwalker** [comment]
test this please

**Comment by aaronwalker** [comment]
retest this please

**Comment by arranubels** [comment]
retest this please

**Comment by arranubels** [comment]
I have made changes to the docker component in the branch of this pull request to support the new Docker hub registry container. Please review.

**Comment by aaronwalker** [comment]
retest this please

**Comment by CpuID** [comment]
:clap:

**Pull request merged**
